### ISSUE TITLE
make a table to track RTP starting

### ISSUE THREAD

**Issue by bhazelton** [HERA-Team/hera_mc#527]
*obsid
*submitted_time (GPS second integer)
jd (integer)
obs_tag ("engineering"/"science")
submitted (boolean)

We'll write a daemon that grabs all non-submitted jobs, breaks into groups of integer JDs and launches RTP on each group. RTP needs to update submitted time or make a new row if it already exists (for a re-run).

**Comment by plaplant** [comment]
@bhazelton thinking about this a bit more, is this a table that will be added to as an observation is added to M&C? If so, then the `submitted_time` column might not initially be filled out, so it probably shouldn't be part of the primary key. But if it's only updated when a job is submitted, then I'm not sure the `submitted` column would be necessary (because it wouldn't be in the table if it hadn't been submitted). I'm leaning toward just removing the `submitted` column, but wanted to get your thoughts.

(Also I'm happy to take over this issue, I have a vested interest in making RTP start-up more reliable and automated 🙂 )

**Comment by bhazelton** [comment]
Yep, I see the problem. One problem is that if we only have obsid as the primary key, then this table can't track re-runs. Another option would be to add a column which tracks iterations, so if it's added by an automated process when the obs is made that could be set to zero and then set to a larger integer for each re-run. Then the submitted_time could be allowed to be null until the job is submitted. It depends on whether you want this table to support re-runs or not.
